# Generated by Django 6.1.1 on 2026-09-07 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'TEAM_MEMBER'}, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
