# Generated by Django 6.1.1 on 2026-09-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_project_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tasks_planned',
            field=models.JSONField(default=list),
        ),
    ]
